### ISSUE TITLE
Docker version show blank page

### ISSUE THREAD

**Issue by thewchan** [standardebooks/web#164] opened 2022-02-04 20:01 UTC
@robinwhittleton It seems that launching the website build via docker stopped working properly; it had worked flawlessly before for me. Does the dockerfile need updating?

**Comment by robinwhittleton** [comment] 2022-02-05 17:34
I’ve just reinstalled it from scratch and it seems to be working fine. Are you getting any error messages_

**Comment by thewchan** [comment] 2022-02-05 21:35
Let me try rebuilding the entire containing one more time.

**Comment by weijia-cheng** [comment] 2022-07-02 20:23
I had the same problem lately, after moving to a new laptop and switched to serving the site locally with Apache.

**Comment by robinwhittleton** [comment] 2022-07-03 14:08
Did it report any errors? It’s working fine for me, so it’s difficult to debug without knowing what the problem is.

**Comment by weijia-cheng** [comment] 2022-07-03 14:22
I saw a `PR_END_OF_FILE_ERROR` in Firefox before reloading it a bit and coming up with nothing. It worked fine on my last laptop.

**Comment by carderne** [comment] 2022-08-09 14:42
I've just cloned the latest version, run `docker build` and when I `docker run` (instructions from the repo) I get a `PR_END_OF_FILE_ERROR` in Firefox, and the following in the Docker logs:

<details closed>
<summary>Click for trace</summary>
<pre>
Generating a RSA private key
..++++
..............................................................++++
writing new private key to '/standardebooks.org/web/config/ssl/standardebooks.test.key'
-----
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-webdriver/webdriver 1.12.1 -> satisfiable by php-webdriver/webdriver[1.12.1].
    - php-webdriver/webdriver 1.12.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-apcu.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-intl.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/25-apcu_bc.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
Enabling site standardebooks.test.
To activate the new configuration, you need to run:
  service apache2 reload
 * Starting Apache httpd web server apache2                                                            * 
 * The apache2 configtest failed.
Output of config test was:
AH00526: Syntax error on line 278 of /etc/apache2/sites-enabled/standardebooks.test.conf:
Invalid command 'XSendFile', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
 * Restarting PHP 7.4 FastCGI Process Manager php-fpm7.4                                       [ OK ] 
</pre>
</details>

**Comment by acabal** [comment] 2022-08-09 14:44
I just added a line to the dockerfile in 42b92bab286fc2096c5db427a9451df5f35309a9 that should fix that.

**Comment by carderne** [comment] 2022-08-09 15:05
That's a bit better, now I get the certificate warning and then an empty page after I click through. Nothing interesting in the console except warnings about `Strict-Transport-Security` and Quirks mode.

**Comment by robinwhittleton** [comment] 2023-01-15 21:28
OK, now I’m seeing the same issue, with a new build based on [colima](https://github.com/abiosoft/colima). Lets me debug it at least 🙂

**Comment by robinwhittleton** [comment] 2023-01-18 17:04
Could people try the Docker instructions again? Alex has merged a patch that should allow composer to download the required packages to get the site running.

(I’d previously managed to install them into the site through macOS, so I hadn’t clocked that the `composer install` inside the Docker VM was failing.)

**Comment by acabal** [comment] 2023-06-06 18:33
Closed due to inactivity

**Closed by acabal** 2023-06-06 18:33 UTC
